/**
 * Danh sach ngan hang/vi dien tu VN pho bien de user chon khi gui yeu cau rut tien (form ngan hang,
 * phan-hoi-cai-thien-trai-nghiem-nguoi-dung.md muc 9). Khong day du 100% ngan hang tai VN, nhung
 * bao gom cac ngan hang thuong dung nhat - KHONG xac thuc gia tri chon co dung thuc te hay khong,
 * chi la danh sach goi y cho <select>, admin tu doi chieu lai qua tin nhan rieng voi user.
 * Momo (2026-08-20, yeu cau truc tiep cua user) - vi dien tu, khong phai ngan hang that, nhung
 * dung chung 1 danh sach/1 field "bankName" de khong phai them field/logic rieng cho vi dien tu.
 */
export const VIETNAM_BANKS: readonly string[] = [
  "Momo",
  "Vietcombank",
  "VietinBank",
  "BIDV",
  "Agribank",
  "Techcombank",
  "MB Bank",
  "ACB",
  "VPBank",
  "Sacombank",
  "TPBank",
  "HDBank",
  "SHB",
  "VIB",
  "Eximbank",
  "OCB",
  "MSB",
  "SeABank",
  "SCB",
  "Bac A Bank",
  "PVcomBank",
  "Nam A Bank",
  "ABBANK",
  "LienVietPostBank",
  "Kienlongbank",
  "BaoVietBank",
  "VietBank",
  "PGBank",
  "NCB",
  "SaigonBank",
  "DongA Bank",
  "CIMB Việt Nam",
  "Shinhan Bank Việt Nam",
  "Standard Chartered Việt Nam",
  "HSBC Việt Nam",
  "Woori Bank Việt Nam",
];
